import { Service } from 'homebridge';
// eslint-disable-next-line max-len
import TuyaDevice, { TuyaDeviceSchema, TuyaDeviceSchemaIntegerProperty, TuyaDeviceSchemaMode, TuyaDeviceSchemaType, TuyaDeviceStatus } from '../../../cloud/device/TuyaDevice';
import BaseAccessory from '../BaseAccessory';
import { configureName } from './Name';
import { configureOn } from './On';
import { configureEnumOn } from './EnumOn';
import { toHapProperty } from '../../util/util';
import { TuyaPlatformDeviceSchemaConfig } from '../../../config';
import { configureRawOn } from './RawOn';

export function configureExtraCharactersitcs(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => {
    return item.code === schema.code;
  });

  if (schemaConfig && schemaConfig.hidden) {
    return;
  }

  if (isExtraSwitch(accessory, schema)) {
    createExtraSwitch(accessory, schema);
  } else if (isExtraEnumSwitch(accessory, schema)) {
    createExtraEnumSwitch(accessory, schema);
  } else if (isExtraSlider(accessory, schema)) {
    createExtraSlider(accessory, schema);
  } else if (isExtraRawSwitch(accessory, schema)) {
    createExtraRawSwitch(accessory, schema);
  }
}

function isExtraSchema(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => {
    return item.code === schema.code;
  });
  if (schemaConfig) {
    if (isExtraCharacteristic(accessory.device, schemaConfig)) { // generated by configureDeviceSpecificFeatures function
      return true;
    } else if (schemaConfig?.extra) { // User-defined
      return true;
    }
    return false;
  }
  if (accessory.supportedDPs.has(schema.code)) {
    return false;
  }
  return true;
}

function isExtraCharacteristic(device: TuyaDevice, schemaConfig: TuyaPlatformDeviceSchemaConfig) {
  if (schemaConfig.newCode === undefined) {
    return false;
  }
  const oldSchema = device.schema.find(schema => {
    // ignore case
    return schema.code.toLowerCase() === schemaConfig.code.toLowerCase();
  });
  const newSchema = device.schema.find(schema => {
    // ignore case
    return schema.code.toLowerCase() === schemaConfig.newCode!.toLowerCase();
  });
  //   console.log('isExtraSchema oldSchema:' + JSON.stringify(oldSchema) + ', newSchema:' + JSON.stringify(newSchema));
  return !oldSchema && newSchema;
}

function isExtraRawSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  if (schema.mode !== 'rw') {
    return false;
  }
  if (schema.type !== TuyaDeviceSchemaType.Raw) {
    return false;
  }
  return isExtraSchema(accessory, schema);
}

function isExtraEnumSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  if (schema.mode !== 'rw') {
    return false;
  }
  if (schema.type !== TuyaDeviceSchemaType.Enum) {
    return false;
  }
  return isExtraSchema(accessory, schema);
}

function isExtraSlider(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  if (schema.mode !== 'rw') {
    return false;
  }
  if (schema.type !== TuyaDeviceSchemaType.Integer) {
    return false;
  }
  return isExtraSchema(accessory, schema);
}

function isExtraSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  if (schema.mode !== 'rw') {
    return false;
  }
  if (schema.type !== TuyaDeviceSchemaType.Boolean) {
    return false;
  }
  return isExtraSchema(accessory, schema);
}

function createExtraSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const service = accessory.accessory.getServiceById(schema.code, schema.code)
        || accessory.accessory.addService(accessory.Service.Switch, schema.code, schema.code);

  configureName(accessory, service, service.displayName);
  configureOn(accessory, service, schema);
  accessory.log.info('add extra switch:' + schema.code
        + ', index:' + accessory.accessory.services.indexOf(service));
}

function createExtraRawSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => {
    return item.code === schema.code;
  });
  const switches = configureRawOn(accessory, schema, schemaConfig?.extraRawSwitch ?? []);
  Object.entries(switches).forEach(([key, value]) => {
    const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => {
      return item.code === key;
    });
    if (schemaConfig && schemaConfig.hidden) {
      accessory.accessory.removeService(value);
    } else {
      accessory.log.info('add extra raw switch:' + schema.code
              + ', enum DP:' + key
              + ', index:' + accessory.accessory.services.indexOf(value));
    }
  },
  );
}

function createExtraEnumSwitch(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const switches = configureEnumOn(accessory, accessory.getSchema(schema.code) ?? schema);
  Object.entries(switches).forEach(([key, value]) => {
    const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => {
      return item.code === key;
    });
    if (schemaConfig && schemaConfig.hidden) {
      accessory.accessory.removeService(value);
    } else {
      accessory.log.info('add extra enum switch:' + schema.code
              + ', enum DP:' + key
              + ', index:' + accessory.accessory.services.indexOf(value));
    }
  },
  );
}

function createExtraSlider(accessory: BaseAccessory, schema: TuyaDeviceSchema) {
  const prop = schema.property as TuyaDeviceSchemaIntegerProperty;

  let service: Service;
  switch (prop.unit) {
    case '℃':
    case '℉':
    case '°C':
    case '°F':
      service = createExtraTemperatureSlider(accessory, schema);
      break;
    default:
      service = createExtraBrightnessSlider(accessory, schema);
  }

  let dummyCode = schema.code + '_switch';

  accessory.log.info('slider switch DPCode:' + dummyCode);
  const schemaConfig = accessory.deviceManager.getDeviceConfig(accessory.device)?.schema?.find(item => item.code === dummyCode);
  if (schemaConfig && schemaConfig.newCode) {
    accessory.log.info('DPCode updated. ' + dummyCode + ' -> ' + schemaConfig.newCode);
    dummyCode = schemaConfig.newCode;
    // to ignore generated dummy code
    schemaConfig.code = dummyCode;
    const dummySchema: TuyaDeviceSchema = {
      code: dummyCode,
      type: TuyaDeviceSchemaType.Boolean,
      mode: TuyaDeviceSchemaMode.READ_WRITE,
      property: {},
    };
    configureOn(accessory, service, dummySchema);
  }

  configureName(accessory, service, schema.code);

  accessory.log.info('add extra slider:' + schema.code
        + ', index:' + accessory.accessory.services.indexOf(service));
}

function createExtraTemperatureSlider(accessory: BaseAccessory, schema: TuyaDeviceSchema): Service {
  // TODO: Tempurature
  return createExtraBrightnessSlider(accessory, schema);
}

function createExtraBrightnessSlider(accessory: BaseAccessory, schema: TuyaDeviceSchema): Service {
  const service = accessory.accessory.getServiceById(schema.code, 'lightbulb_' + schema.code)
        || accessory.accessory.addService(accessory.Service.Lightbulb, schema.code, 'lightbulb_' + schema.code);

  const props = toHapProperty(schema.property);
  service.getCharacteristic(accessory.Characteristic.Brightness)
    .onGet(() => {
      const value = Number(accessory.getStatus(schema.code)?.value) || 0;
      return value;
    })
    .onSet(async value => {
      const commands: TuyaDeviceStatus[] = [];
      commands.push({ code: schema.code, value: Number(value) });
      await accessory.sendCommands(commands, true);
    })
    .setProps(props);

  return service;
}